# Generated by Django 3.1.6 on 2026-02-15 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='origination_state',
            field=models.CharField(default='MA', max_length=2),
        ),
    ]
