# Generated by Django 3.1.6 on 2026-02-15 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0002_add_origination_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='car_make',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='person',
            name='car_model',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='person',
            name='photo',
            field=models.CharField(blank=True, help_text='Path to driver photo in static or URL', max_length=255),
        ),
        migrations.AddField(
            model_name='person',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Price per seat (TBD if null)', max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=0, help_text='Driver rating 0–5', max_digits=2),
        ),
        migrations.AlterField(
            model_name='person',
            name='origination_state',
            field=models.CharField(max_length=2),
        ),
    ]
