# Generated by Django 3.1.6 on 2026-02-15 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0003_driver_profile_and_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registrant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('profile_pic', models.FileField(blank=True, null=True, upload_to='registrants/')),
            ],
        ),
    ]
