# Generated by Django 3.1.6 on 2026-02-15 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0005_ride_request_and_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrant',
            name='City',
            field=models.CharField(default='Boston', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registrant',
            name='State',
            field=models.CharField(default='MA', max_length=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='registrant',
            name='phone',
            field=models.CharField(help_text='Exactly 10 digits', max_length=10),
        ),
    ]
