# Generated by Django 3.1.6 on 2026-02-22 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0006_auto_20260215_1934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='driver_photos/'),
        ),
    ]
