# Generated by Django 6.0.2 on 2026-03-01 19:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rides", "0008_userprofile"),
    ]

    operations = [
        migrations.CreateModel(
            name="EventPass",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=32, unique=True)),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("conference", "Conference"),
                            ("marathon", "Marathon"),
                        ],
                        max_length=16,
                    ),
                ),
                ("event_name", models.CharField(max_length=128)),
                ("full_name", models.CharField(max_length=128)),
                ("phone", models.CharField(blank=True, default="", max_length=10)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("destination_city", models.CharField(max_length=64)),
                ("destination_state", models.CharField(max_length=2)),
                ("redeemed_at", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name="person",
            name="atmosphere_preferences",
            field=models.CharField(blank=True, default="", max_length=128),
        ),
        migrations.AddField(
            model_name="person",
            name="atmospheric_conditions",
            field=models.CharField(
                blank=True,
                help_text="What are the drivers preferred atmospheric conditions? (e.g. talkative, quiet, music-friendly, etc.)",
                max_length=64,
            ),
        ),
        migrations.AddField(
            model_name="person",
            name="chat_allowed",
            field=models.BooleanField(
                default=False, help_text="Is chat allowed in the car?"
            ),
        ),
        migrations.AddField(
            model_name="person",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="person",
            name="last_name",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
        migrations.AddField(
            model_name="person",
            name="luggage_available",
            field=models.BooleanField(
                default=False, help_text="Does the driver have luggage space available?"
            ),
        ),
        migrations.AddField(
            model_name="person",
            name="service_level",
            field=models.CharField(
                choices=[
                    ("regular", "Regular CartyCity"),
                    ("premium", "Premium CartyCity"),
                ],
                default="regular",
                max_length=12,
            ),
        ),
        migrations.AddField(
            model_name="person",
            name="vehicle_type",
            field=models.CharField(
                choices=[
                    ("sedan", "Sedan"),
                    ("suv", "SUV"),
                    ("van", "Van"),
                    ("truck", "Truck"),
                    ("other", "Other"),
                ],
                default="sedan",
                max_length=12,
            ),
        ),
        migrations.CreateModel(
            name="RideReview",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rating", models.PositiveSmallIntegerField()),
                ("comment", models.CharField(blank=True, default="", max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "driver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="rides.person",
                    ),
                ),
            ],
        ),
    ]
